### PR TITLE
Allow disable table level stats

### PR DESCRIPTION
**Pull request by YuzeLiao**
will not merge until agent changes are merged.

### CODE REVIEW

**Review by nappelson — APPROVED** [review]
@YuzeLiao is this required for any of our users?

Also, can we be sure to make the equivalent changes for the other deployment methods to keep them in sync? (docker, helm, kubernetes)? I know that is a good amount of work so feel free to get help :D

**Comment by YuzeLiao** [comment]
> @YuzeLiao is this required for any of our users?

I guess discussed with @bohanjason some user may want to disable table level stats for concerns like performance (although it's really light-weight) so we want to provide the option. 

Yes, will update the other sources.

**Review by nappelson — CHANGES_REQUESTED** [review]
@YuzeLiao oh if that is the case, can we just not have this option and wait until a user requests it? If performance is the only concern and it is light weight, I think we should not provide the option as it is just one more thing to maintain.

**Comment by YuzeLiao** [comment]
@nappelson OK will close the pr. and this will be a hidden config so when a user needs it we can still disable it

**Pull request closed without merging**
